// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgdfh4SslUIdyumG7jqBymFAih1_hOMnE',
    appId: '1:804425004584:web:7113bf844386b2b8b0e71d',
    messagingSenderId: '804425004584',
    projectId: 'detoxium-69d63',
    authDomain: 'detoxium-69d63.firebaseapp.com',
    storageBucket: 'detoxium-69d63.firebasestorage.app',
    measurementId: 'G-1VZWCLNWMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX8XD0eiD_cIhtNvVwGku0oilTZ6dwIhc',
    appId: '1:804425004584:android:34bdabe8b66be70db0e71d',
    messagingSenderId: '804425004584',
    projectId: 'detoxium-69d63',
    storageBucket: 'detoxium-69d63.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgdfh4SslUIdyumG7jqBymFAih1_hOMnE',
    appId: '1:804425004584:web:df456c5fc1a9cb59b0e71d',
    messagingSenderId: '804425004584',
    projectId: 'detoxium-69d63',
    authDomain: 'detoxium-69d63.firebaseapp.com',
    storageBucket: 'detoxium-69d63.firebasestorage.app',
    measurementId: 'G-V4MDLMB57Q',
  );
}
